---

- hosts: all
  become: true
  tasks:

  - name: Update the local repository index
    apt:
      update_cache: yes
    when: ansible_distribution in ["Debian", "Ubuntu"]

  - name: Install the NGiNX package
    apt:
      name: nginx
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install Certbot to easily install Letsencrypt SSL certificates
    apt:
      name: certbot
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Update the local repository index
    dnf:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install the Apache2 package
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == "CentOS"

  - name: Install Certbot to easily install Letsencrypt SSL certificates
    dnf:
      name: certbot
      state: latest
    when: ansible_distribution == "CentOS"

