---

- hosts: all
  become: true
  tasks:

  - name: Update the local repository index
    apt:
      update_cache: yes

  - name: Remove the NGiNX package
    apt:
      name: nginx
      state: absent

  - name: Remove Certbot to easily install Letsencrypt SSL certificates
    apt:
      name: certbot
      state: absent
